config/routes.rb
Rails.application.routes.draw do
  
  resources :stores

  root'items#index'

  resources :users

  resources :categories

  resources :suppliers

  resources :purchase_orders

  resources :locations

  resources :invoices

  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base

	belongs_to :user
	belongs_to :category
	belongs_to :invoice
	belongs_to :supplier
	belongs_to :purchase_order
	belongs_to :store

	validate :user_or_store

	private
	  def user_or_store
	  	if !(user.blank? ^ store.blank?)
	  	  errors[:base] << "Select User or Store, and not both"
	  end
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.store_id = 1    # Set default store
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:user_id, :store_id, :allocation_date, :label, :manufacturer, :model, :description, :serial, :purchased, :category_id, :invoice_id, :purchase_order_id, :warranty, :price, :supplier_id, :disposed, :comment)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => "form-horizontal item" } do |f| %>

    <% if @item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :user_id, User.all.map { |t| [t.name, t.id]}, {:class => 'form-control', include_blank: ""} %>
    </div>
    <%= error_span(@item[:user_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :store_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :store_id, Store.all.map { |t| [t.description, t.id]}, {:class => 'form-control', include_blank: ""} %>
    </div>
    <%= error_span(@item[:store_id]) %>
  </div>  
  <div class="control-group">
    <%= f.label :allocation_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :allocation_date, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:allocation_date]) %>
  </div>
  <div class="control-group">
    <%= f.label :label, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :label, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:label]) %>
  </div>
  <div class="control-group">
    <%= f.label :manufacturer, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :manufacturer, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:manufacturer]) %>
  </div>
  <div class="control-group">
    <%= f.label :model, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :model, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:model]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :serial, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :serial, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:serial]) %>
  </div>
  <div class="control-group">
    <%= f.label :purchased, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :purchased, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:purchased]) %>
  </div>
  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category_id, Category.all.map { |t| [t.description, t.id]}, {:class => 'form-control'} %>
    </div>
    <%= error_span(@item[:category_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :invoice_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :invoice_id, Invoice.all.map { |t| [t.number, t.id]}, {:class => 'form-control', include_blank: "unknown"} %>
    </div>
    <%= error_span(@item[:invoice_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :purchase_order_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :purchase_order_id, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:purchase_order_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :warranty, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :warranty, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:warranty]) %>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:price]) %>
  </div>
  <div class="control-group">
    <%= f.label :supplier_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :supplier_id, Supplier.all.map { |t| [t.name, t.id]}, {:class => 'form-control', include_blank: "unknown"} %>
    </div>
    <%= error_span(@item[:supplier_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :disposed, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :disposed, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:disposed]) %>
  </div>
  <div class="control-group">
    <%= f.label :comment, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :comment, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:comment]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            items_path, :class => 'btn btn-default' %>

<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:label) %></th>
      <th><%= model_class.human_attribute_name(:manufacturer) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:serial) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:store_id) %></th>
      <th><%= model_class.human_attribute_name(:allocation_date) %></th>
      <th><%= model_class.human_attribute_name(:purchased) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>

      <th><%= model_class.human_attribute_name(:supplier_id) %></th>
      <th><%= model_class.human_attribute_name(:disposed) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.label, item_path(item) %></td>
        <td><%= item.manufacturer %></td>
        <td><%= item.model %></td>
        <td><%= item.description %></td>
        <td><%= link_to item.serial, item_path(item) %></td>
        <td><%= (link_to item.user.name, user_path(item)) if item.user.try(:name) %></td>
        <td><%= item.store.try(:description) %></td>
        <td><%= item.allocation_date %></td>
        <td><%= item.purchased %></td>
        <td><%= item.category.try(:description) %></td>

        <td><%= (link_to item.supplier.name, supplier_path(item)) if item.supplier.try(:name) %></td>
        <td><%= item.disposed %></td>
        <td><%= item.comment %></td>

        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      item_path(item), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @item.user.try(:name) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:store_id) %>:</strong></dt>
  <dd><%= @item.store.try(:description) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:allocation_date) %>:</strong></dt>
  <dd><%= @item.allocation_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:label) %>:</strong></dt>
  <dd><%= @item.label %></dd>
  <dt><strong><%= model_class.human_attribute_name(:manufacturer) %>:</strong></dt>
  <dd><%= @item.manufacturer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @item.model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @item.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serial) %>:</strong></dt>
  <dd><%= @item.serial %></dd>
  <dt><strong><%= model_class.human_attribute_name(:purchased) %>:</strong></dt>
  <dd><%= @item.purchased %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @item.category.try(:description) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:invoice_id) %>:</strong></dt>
  <dd><%= @item.invoice.try(:number) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:purchase_order_id) %>:</strong></dt>
  <dd><%= @item.purchase_order.try(:number) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:warranty) %>:</strong></dt>
  <dd><%= @item.warranty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @item.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:supplier_id) %>:</strong></dt>
  <dd><%= @item.supplier.try(:name) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:disposed) %>:</strong></dt>
  <dd><%= @item.disposed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @item.comment %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>