config/routes.rb
Rails.application.routes.draw do
  
  resources :stores

  root'items#index'

  resources :users

  resources :categories

  resources :suppliers

  resources :purchase_orders

  resources :locations

  resources :invoices

  resources :items

end

app/models/location.rb
class Location < ActiveRecord::Base

	has_many :users

	validates_presence_of :name
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all.order(:name)
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
    @location.country = "Australia"   # Set default country
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :phone, :street1, :street2, :town, :state, :postcode, :country, :comment)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for @location, :html => { :class => "form-horizontal location" } do |f| %>

    <% if @location.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @location.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@location[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%= error_span(@location[:phone]) %>
  </div>
  <div class="control-group">
    <%= f.label :street1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :street1, :class => 'form-control' %>
    </div>
    <%= error_span(@location[:street1]) %>
  </div>
  <div class="control-group">
    <%= f.label :street2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :street2, :class => 'form-control' %>
    </div>
    <%= error_span(@location[:street2]) %>
  </div>
  <div class="control-group">
    <%= f.label :town, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :town, :class => 'form-control' %>
    </div>
    <%= error_span(@location[:town]) %>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <%= error_span(@location[:state]) %>
  </div>
  <div class="control-group">
    <%= f.label :postcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :postcode, :class => 'form-control' %>
    </div>
    <%= error_span(@location[:postcode]) %>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'form-control' %>
    </div>
    <%= error_span(@location[:country]) %>
  </div>
  <div class="control-group">
    <%= f.label :comment, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :comment, :class => 'form-control' %>
    </div>
    <%= error_span(@location[:comment]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            locations_path, :class => 'btn btn-default' %>

<% end %>

app/views/locations/edit.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/index.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:street1) %></th>
      <th><%= model_class.human_attribute_name(:street2) %></th>
      <th><%= model_class.human_attribute_name(:town) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:postcode) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.name, location_path(location) %></td>
        <td><%= location.phone %></td>
        <td><%= location.street1 %></td>
        <td><%= location.street2 %></td>
        <td><%= location.town %></td>
        <td><%= location.state %></td>
        <td><%= location.postcode %></td>
        <td><%= location.country %></td>
        <td><%= location.comment %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_location_path(location), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      location_path(location),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_location_path,
            :class => 'btn btn-primary' %>

app/views/locations/new.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/show.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @location.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @location.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:street1) %>:</strong></dt>
  <dd><%= @location.street1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:street2) %>:</strong></dt>
  <dd><%= @location.street2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:town) %>:</strong></dt>
  <dd><%= @location.town %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @location.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postcode) %>:</strong></dt>
  <dd><%= @location.postcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @location.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @location.comment %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              locations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_location_path(@location), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              location_path(@location),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>