config/routes.rb
Rails.application.routes.draw do
  
  resources :stores

  root'items#index'

  resources :users

  resources :categories

  resources :suppliers

  resources :purchase_orders

  resources :locations

  resources :invoices

  resources :items

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items

    validates_presence_of :description
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

	has_many :items
	belongs_to :supplier

	validates_presence_of :number, :date, :supplier
end

app/models/item.rb
class Item < ActiveRecord::Base

	belongs_to :user
	belongs_to :category
	belongs_to :invoice
	belongs_to :supplier
	belongs_to :purchase_order
	belongs_to :store

	validate :user_or_store

	private
	  def user_or_store
	  	if !(user.blank? ^ store.blank?)
	  	  errors[:base] << "Select User or Store, and not both"
	  end
	end
end

app/models/location.rb
class Location < ActiveRecord::Base

	has_many :users

	validates_presence_of :name
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base

	has_many :items

	validates_presence_of :number, :date, :supplier
end

app/models/store.rb
class Store < ActiveRecord::Base

	has_many :items

	validates_presence_of :description
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base

	has_many :items

	validates_presence_of :name, :phone
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :items
	belongs_to :location

    validates_presence_of :location
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.store_id = 1    # Set default store
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:user_id, :store_id, :allocation_date, :label, :manufacturer, :model, :description, :serial, :purchased, :category_id, :invoice_id, :purchase_order_id, :warranty, :price, :supplier_id, :disposed, :comment)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all.order(:description)
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :location_id, :phone, :mobile, :email, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assets</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= bootstrap_flash %>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
      <div class="navbar-header">
	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-nav">
		  <a>Menu</a>
	    </button>
	  </div>
	  <a class="navbar-brand">Asset Register</a>
      <div class="collapse navbar-collapse" id="collapse-nav">  
        <ul class="nav navbar-nav">         
          <li class="<%= is_active?(items_path) %>"><%= link_to "Items", items_path %></li>
          <li class="<%= is_active?(invoices_path) %>"><%= link_to "Invoices", invoices_path %></li>
          <li class="<%= is_active?(suppliers_path) %>"><%= link_to "Suppliers", suppliers_path %></li>
          <li class="<%= is_active?(users_path) %>"><%= link_to "Users", users_path %></li>
          <li class="<%= is_active?(stores_path) %>"><%= link_to "Stores", stores_path %></li>
          <li class="<%= is_active?(locations_path) %>"><%= link_to "Locations", locations_path %></li>
          <li class="<%= is_active?(categories_path) %>"><%= link_to "Categories", categories_path %></li>
          <li class="dropdown">

            <a class="dropdown-toggle" data-toggle="dropdown">About <span class="caret"></span></a>
      	    <ul class="dropdown-menu" role="menu">

      		  <p class="padside_10">
      	        Track Assets and Stuff.</br>
      	        See who didn't return the stuff</br> 
      	        when they resigned.</br></br>
      	        Don't like this DB?</br>
			          Your welcome to fork it.
      	  	  </p>
      	    </ul>
          </li>
        </ul>

      </div>
    </div>
  </div>                  <!-- end of NavBar -->
  <div class="container-fluid">
  <%= yield %>
  </div>

</body>
</html>